# Generated by Django 6.0 on 2025-12-11 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Use this to disable a table without deleting it.'),
        ),
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.CharField(choices=[('WINDOW', 'Window'), ('CENTRAL', 'Central floor'), ('CORNER', 'Corner booth'), ('OUTSIDE', 'Outside')], default='CENTRAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(editable=False, help_text='Code used by customer to manage / cancel booking.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_app.table'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('table', 'date', 'time'), name='unique_table_timeslot'),
        ),
    ]
